# Generated by Django 2.1.2 on 2018-12-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
