# Generated by Django 2.1.2 on 2018-12-14 02:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20181214_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
